name: first pipeline

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: print Message
        run: echo "Hello World"

  hi:
    runs-on: ubuntu-latest

    steps:
      - name: print Message
        run: echo "Hi World"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Check numpy version
        run: python -c "import numpy; print(numpy.__version__)"
        

      - name: print Message
        run: echo "Build Success - requirements installed"
